name: 2a_grab_roller
agent_num: 2

image_shape: &image_shape [3, 256, 256]
action_shape: &action_shape [14]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs: 
    cam_high:
      shape: *image_shape
      type: rgb
    qpos:
      shape: *action_shape
      type: low_dim
  action:
    shape: *action_shape

dataset:
  _target_: dataset.dataset2d_real.Dataset2D
  dataset_path: /home/wenxin/office/EDP_real/grab_roller_dual.h5
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  input_meta: 
    obs:
      cam_high: *image_shape
      qpos: *action_shape
    action: *action_shape
  seperate_action: False
  use_mem: False
  
