defaults:
  - _self_
  - task: default_task

name: ${task.name}
task_name: ${task.name}
shape_meta: ${task.shape_meta}
policy_name: DDP2
info: 

seed: 42

# coarse和fine单独设置
coarse_horizon: 7
internal: 4


horizon: -1
n_action_steps: ${policy.fine_dp.n_action_steps}
n_obs_steps: 2
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True
past_action_visible: False
obs_only_n_steps: False

policy:
  _target_: source.policy.ddp2.DDP2
  optimizer_cfg: ${optimizer}
  scheduler_cfg: ${lr_scheduler}
  num_epochs_coarse: ${training.num_epochs_coarse}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}

  coarse_dp:
    _target_: source.policy.ddp2_coarse.Coarse_DP2
    use_point_crop: true
    condition_type: cross_attention_add

    diffusion_step_embed_dim: 128
    crop_shape:
    - 80
    - 80
    encoder_output_dim: 128
    horizon: ${coarse_horizon}
    internal: ${internal}
    n_action_steps: ${coarse_horizon}
    n_obs_steps: ${n_obs_steps}

    noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      clip_sample: True
      set_alpha_to_one: True
      steps_offset: 0
      prediction_type: sample
    
    obs_encoder:
      _target_: source.model.DDP2.multi_image_obs_encoder.MultiImageObsEncoder
      shape_meta: ${shape_meta}
      rgb_model:
        _target_: source.model.DDP2.model_getter.get_resnet
        name: resnet18
        weights: null
      resize_shape: null
      crop_shape: null
      # constant center crop
      random_crop: True
      use_group_norm: True
      share_rgb_model: False
      imagenet_norm: True

    num_inference_steps: 10
    obs_as_global_cond: true
    shape_meta: ${shape_meta}

    debug: ${training.debug} 

  fine_dp:
    _target_: source.policy.ddp2_fine.Fine_DP2
    use_point_crop: true
    condition_type: cross_attention_add

    diffusion_step_embed_dim: 128
    crop_shape:
    - 80
    - 80
    encoder_output_dim: 128
    horizon: ${eval:${internal} + 3}
    internal: ${internal}
    n_action_steps: ${internal}
    n_obs_steps: ${n_obs_steps}

    noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      clip_sample: True
      set_alpha_to_one: True
      steps_offset: 0
      prediction_type: sample

    obs_encoder:
      _target_: source.model.DDP2.multi_image_obs_encoder.MultiImageObsEncoder
      shape_meta: ${shape_meta}
      rgb_model:
        _target_: source.model.DDP2.model_getter.get_resnet
        name: resnet18
        weights: null
      resize_shape: null
      crop_shape: null
      # constant center crop
      random_crop: True
      use_group_norm: True
      share_rgb_model: False
      imagenet_norm: True

    num_inference_steps: 10
    obs_as_global_cond: true
    shape_meta: ${shape_meta}

    debug: ${training.debug}  

  debug: ${training.debug}


ema:
  decay: 0.99
  update_every_n_steps: 1

dataloader:
  train:
    batch_size: 128
    num_workers: 4
    shuffle: True
    pin_memory: True
    persistent_workers: True
  val:
    batch_size: 128
    num_workers: 4
    shuffle: False
    pin_memory: True
    persistent_workers: True

optimizer:
  transformer_weight_decay: 1.0e-3
  obs_encoder_weight_decay: 1.0e-6
  lr: 1.0e-4
  betas: [0.9, 0.95]

lr_scheduler:
  scheduler: cosine
  warmup_steps: 500

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/loss
  mode: min
  save_top_k: 5
  save_last: True
  save_weights_only: False
  every_n_epochs: 100
  save_on_train_epoch_end: False
  filename: 'epoch={epoch:0>3d}-loss={val/loss:.4f}'
  auto_insert_metric_name: False

trainer:
  max_epochs: 500
  accelerator: auto
  devices: 1
  precision: 32
  check_val_every_n_epoch: 1
  enable_progress_bar: True
  profiler: "simple"

  
training: # 用于存放trainer没有的参数
  num_epochs_coarse: -1
  debug: False
  seed: ${seed}
  progress_bar_refresh_rate: 10

logging:
  project: DP_real
  group: ${policy_name}_${task_name}
  name: ${policy_name}_${task_name}_${now:%Y.%m.%d-%H.%M.%S}_${info}
  mode: online
  tags: ["${task_name}", "${policy_name}"]

multi_run:
  run_dir: _outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: _outputs/${policy_name}/${task_name}/${now:%Y.%m.%d.%H.%M.%S}
  sweep:
    dir: _outputs/${policy_name}/${task_name}/${now:%Y.%m.%d.%H.%M.%S}
    subdir: ${hydra.job.num}
