defaults:
  - _self_
  - task: default_task

name: ${task.name}
task_name: ${task.name}
shape_meta: ${task.shape_meta}
dp_name: EDP2

# coarse和fine单独设置
horizon: -1
n_action_steps: ${policy.fine_dp.n_action_steps}

coarse_horizon: 8
internal: 16
use_topp: False

seed: ${training.seed}

n_obs_steps: 2
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True
past_action_visible: False

policy:
  _target_: policy.edp2.DDP2
  optimizer_cfg: ${optimizer}
  scheduler_cfg: ${lr_scheduler}
  num_epochs_coarse: ${training.num_epochs_coarse}
  use_topp: ${use_topp}

  coarse_dp:
    _target_: policy.edp2_coarse.Coarse_DP2
    use_point_crop: true
    condition_type: cross_attention_add

    diffusion_step_embed_dim: 128
    crop_shape:
    - 80
    - 80
    encoder_output_dim: 128
    horizon: ${coarse_horizon}
    internal: ${internal}
    n_action_steps: ${coarse_horizon}
    n_obs_steps: ${n_obs_steps}

    noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      clip_sample: True
      set_alpha_to_one: True
      steps_offset: 0
      prediction_type: sample
    
    obs_encoder:
      _target_: model.vision.multi_image_obs_encoder.MultiImageObsEncoder
      shape_meta: ${shape_meta}
      rgb_model:
        _target_: model.vision.model_getter.get_resnet
        name: resnet18
        weights: null
      resize_shape: null
      crop_shape: null
      # constant center crop
      random_crop: True
      use_group_norm: True
      share_rgb_model: False
      imagenet_norm: True

    num_inference_steps: 10
    obs_as_global_cond: true
    shape_meta: ${shape_meta}

    debug: ${training.debug} 

  fine_dp:
    _target_: policy.edp2_fine.Fine_DP2
    use_point_crop: true
    condition_type: cross_attention_add

    diffusion_step_embed_dim: 128
    crop_shape:
    - 80
    - 80
    encoder_output_dim: 128
    horizon: ${eval:${internal} + 3}
    internal: ${internal}
    n_action_steps: ${internal}
    n_obs_steps: ${n_obs_steps}

    noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      clip_sample: True
      set_alpha_to_one: True
      steps_offset: 0
      prediction_type: sample

    obs_encoder:
      _target_: model.vision.multi_image_obs_encoder.MultiImageObsEncoder
      shape_meta: ${shape_meta}
      rgb_model:
        _target_: model.vision.model_getter.get_resnet
        name: resnet18
        weights: null
      resize_shape: null
      crop_shape: null
      # constant center crop
      random_crop: True
      use_group_norm: True
      share_rgb_model: False
      imagenet_norm: True

    num_inference_steps: 10
    obs_as_global_cond: true
    shape_meta: ${shape_meta}

    debug: ${training.debug}  

  debug: ${training.debug}


ema:
  update_after_steps: 0

dataloader:
  train:
    batch_size: 128
    num_workers: 4
    shuffle: True
    pin_memory: True
    persistent_workers: True
  val:
    batch_size: 128
    num_workers: 4
    shuffle: False
    pin_memory: True
    persistent_workers: True

optimizer:
  transformer_weight_decay: 1.0e-3
  obs_encoder_weight_decay: 1.0e-6
  lr: 1.0e-4
  betas: [0.9, 0.95]

lr_scheduler:
  scheduler: cosine
  warmup_steps: 500

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: train/loss
  # monitor: rollout/success_rate
  mode: min
  # mode: max
  save_top_k: -1
  save_last: True
  save_weights_only: False
  every_n_epochs: 100
  save_on_train_epoch_end: False
  filename: 'epoch={epoch:0>3d}-loss={train/loss:.4f}.ckpt'
  # filename: 'epoch={epoch:0>3d}-success_rate={rollout/success_rate:.4f}.ckpt'
  auto_insert_metric_name: False

trainer:
  max_epochs: 1000
  accelerator: auto
  devices: 1
  precision: 32
  check_val_every_n_epoch: 10
  enable_progress_bar: True
  profiler: "simple"

  
training: # 用于存放trainer没有的参数
  num_epochs_coarse: -1
  debug: False
  seed: 42
  progress_bar_refresh_rate: 10
  
logging:
  project: ${dp_name}_REAL
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}
  tags: ["${task_name}"]
  id: null
  group: null
  save_code: True

multi_run:
  run_dir: _outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: _outputs/${dp_name}/${task_name}/${now:%Y.%m.%d.%H.%M.%S}
  sweep:
    dir: _outputs/${dp_name}/${task_name}/${now:%Y.%m.%d.%H.%M.%S}
    subdir: ${hydra.job.num}
